name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Install LLVM Toolchain
        run: |
          sudo apt update
          sudo apt install -y wget gnupg lsb-release software-properties-common
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 17

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y clang-17 libc++-17-dev libc++abi-17-dev cmake build-essential fasm libfmt-dev
          sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-17 100
          sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-17 100

      - name: Verify Compiler and Standard Library
        run: |
          clang++ --version
          echo | clang++ -E -dM - | grep __cplusplus
          ls /usr/include/c++/v1/ | grep fstream || echo "<fstream> not found!"

      - name: Create Build Environment
        run: |
          mkdir -p build
          cd build
          cmake ..

      - name: Build
        run: |
          cd build
          make

      - name: Run Valgrind
        run: |
          valgrind --leak-check=full --error-exitcode=1 ./build/.epsilang

      - name: Commit and Push Formatting Changes (if any)
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          find . -name '*.c' -o -name '*.h' | xargs clang-format -i -style=file
          git add .
          if git diff --cached --exit-code; then
            echo "No formatting changes detected."
          else
            git commit -m "Apply clang-format style changes"
            git push
          fi
