name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y clang-format valgrind cmake build-essential fasm clang
          sudo apt install -y libfmt-dev  # Install fmt library

      - name: Check formatting
        run: |
          find . -name '*.c' -o -name '*.h' | xargs clang-format --dry-run -style=file

      - name: Auto-correct formatting
        run: |
          find . -name '*.c' -o -name '*.h' | xargs clang-format -i -style=file

      - name: Commit and push changes if any
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          if git diff --cached --exit-code; then
            echo "No formatting changes detected."
          else
            git commit -m "Apply clang-format style changes"
            git push
          fi

      - name: Create CMake environment
        run: |
          mkdir -p build
          cd build
          cmake .. -DCMAKE_CXX_STANDARD=20

      - name: Build
        run: |
          cd build
          make

      - name: Run Valgrind
        run: |
          valgrind --leak-check=full --error-exitcode=1 ./build/.epsilang
